groups/urls.py
from django.conf.urls import url

from . import views

app_name = 'groups'

urlpatterns = [
    url(r"^$", views.ListGroups.as_view(), name="all"),
    url(r"^new/$", views.CreateGroup.as_view(), name="create"),
    url(r"^posts/in/(?P<slug>[-\w]+)/$",views.SingleGroup.as_view(),name="single"),
    url(r"join/(?P<slug>[-\w]+)/$",views.JoinGroup.as_view(),name="join"),
    url(r"leave/(?P<slug>[-\w]+)/$",views.LeaveGroup.as_view(),name="leave"),
]

posts/urls.py
from django.conf.urls import url

from . import views

app_name='posts'

urlpatterns = [
    url(r"^$", views.PostList.as_view(), name="all"),
    url(r"new/$", views.CreatePost.as_view(), name="create"),
    url(r"by/(?P<username>[-\w]+)/$",views.UserPosts.as_view(),name="for_user"),
    url(r"by/(?P<username>[-\w]+)/(?P<pk>\d+)/$",views.PostDetail.as_view(),name="single"),
    url(r"delete/(?P<pk>\d+)/$",views.DeletePost.as_view(),name="delete"),
]

socialmedia/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.HomePage.as_view(), name='home'),
    url(r'^accounts/', include('accounts.urls'), name = 'accounts'),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^test/$', views.TestPage.as_view(), name = 'test'),
    url(r'^thanks/$', views.ThanksPage.as_view(), name = 'thanks'),
    url(r'^editor/$', views.EditorPage.as_view(), name = 'editor'),
    url(r"^posts/", include("posts.urls", namespace="posts")),
    url(r"^groups/",include("groups.urls", namespace="groups")),
]

groups/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.
from django.urls import reverse 
#to allow markdoen inside posts


from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length = 255, unique = True)
    slug = models.SlugField(allow_unicode = True, unique = True)
    description = models.TextField(blank = True, default = '')
    members = models.ManyToManyField(User, through = 'GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs = {'slug':self.slug})

    class Meta:
        ordering = ['name']


class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name = 'memberships', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name = 'user_groups', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

groups/views.py
from django.shortcuts import render
from django.contrib import messages

# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from django.db import IntegrityError
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import generic
from . import models
from groups.models import Group, GroupMember

class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    model = Group

class SingleGroup(generic.DetailView):
    model = Group


class ListGroups(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin, generic.RedirectView):

    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group,slug=self.kwargs.get("slug"))

        try:
            GroupMember.objects.create(user=self.request.user,group=group)

        except IntegrityError:
            messages.warning(self.request,("Warning, already a member of {}".format(group.name)))

        else:
            messages.success(self.request,"You are now a member of the {} group.".format(group.name))

        return super().get(request, *args, **kwargs)


class LeaveGroup(LoginRequiredMixin, generic.RedirectView):
    # where to direct once the actoin is performed
    def get_redirect_url(self, *args, **kwargs):
        return reverse("groups:single",kwargs={"slug": self.kwargs.get("slug")})

    def get(self, request, *args, **kwargs):

        try:

            membership = models.GroupMember.objects.filter(
                user=self.request.user,
                group__slug=self.kwargs.get("slug")
            ).get()

        except models.GroupMember.DoesNotExist:
            messages.warning(
                self.request,
                "You can't leave this group because you aren't in it."
            )
        else:
            membership.delete()
            messages.success(
                self.request,
                "You have successfully left this group."
            )
        return super().get(request, *args, **kwargs)

groups/templates/groups/group_base.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
  <div class="row">
    {% block pregroup %}{% endblock %}
    {% block group_content %}{% endblock %}
    {% block postgroup %}{% endblock %}
  </div>
</div>

{% endblock %}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}
{% load static %}
{% block pregroup %}
<style type="text/css">
    .ri{
      float:right;
    }
    .le{
      float:left;
      width:30%;
    }
    .p{
      border:1px solid grey;
      border-radius: 25px;
      padding:10px;
    }
    .i{
      width:60%;
    }

</style>
<div class="le">
  <h1>{{group.name}}</h1>
  <h2>MemberCount:{{group.members.count}}</h2>

  <div class="content">
    {% if user in group.members.all %}
      <a href="{% url 'groups:leave' slug=group.slug %}"
          class = 'btn btn-lg btn-fill btn-warning'><span
          class = 'glyphicon glyphicon-remove-circle'>Leave</span></a>

    {% else %}
    <a href="{% url 'groups:join' slug=group.slug %}"
        class = 'btn btn-lg btn-fill btn-warning'><span
        class = 'glyphicon glyphicon-ok-circle'>Join</span></a>

    {% endif %}

  </div>
</div>

{% endblock %}

{% block group_content %}
<div class="col-md-8 ri">
	{% if group.posts.count == 0 %}

	<h1>No posts in this group yet!!!</h1>
  <img class="i" src="{% static 'images/12.png'%}">

	{% else %}
    <h2 style = 'text-align:center'><strong>Posts in this group:</strong></h2>
		{% for post in group.posts.all %}
      <!-- injecting html in here -->
      <div class="p">
        {% include "posts/_post.html" %}

      </div>
      <br>

		{% endfor %}

	{% endif %}
</div>

{% endblock %}

groups/templates/groups/group_form.html
{% extends "groups/group_base.html" %}
{% load bootstrap3 %}
{% load static %}
{% block group_content %}

<style type="text/css">
  .i{
    width:50%;
    float:left;
  }
  textarea {
   resize: none;
 }
</style>
<div class="i">
  <h2>Create A New Group</h2>
    <form method="POST" action="{% url 'groups:create' %}" id="groupForm">
    	{% csrf_token %}
    	{% bootstrap_form form %}
    	<input type="submit" value="Create" class="btn btn-primary btn-large">
    </form>
</div>

<img class="i" src="{% static 'images/2.png'%}">
{% endblock %}

groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}

<style type="text/css">
	#c{
		text-align:center;
		border:1px solid black;
		border-radius:25px;
		width:40%;
	}
</style>
<div class="col-md-4">
	<div class="content">
		{% if user.is_authenticated %}
		<h2>
			Welcome back
			<a href="{% url 'posts:for_user' username=user.username %}">@{{user.username }}</a>
		</h2>

    {% endif %}
			<h2 id="c">Groups</h2>

			<h4 style = 'color:grey'>Welcome to the Groups Page! Select a Group of your interest!</h4>
	</div>
	{% if user.is_authenticated %}
	<a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning"><span class="glyphicon glyphicon-plus-sign"></span> Create New Group!</a>
	{% endif %}
</div>
{% endblock %}


{% block group_content %}
<div class="col-md-8">
	<div class="list-group">
		{% for group in object_list %}
		  <a class="list-group-item" href="{% url 'groups:single' slug=group.slug %}">
			     <h3 class="title list-group-item-heading" style="color:blue">{{ group.name }}</h3>
			<div class="list-group-item-text container-fluid" style="color:#36648B">
				{{ group.description }}
				<div class="row">
					<div class="col-md-4">
						<span class="badge">{{ group.members.count }}</span> member{{ group.members.count|pluralize }}
					</div>
					<div class="col-md-4">
						<span class="badge">{{ group.posts.count }}</span> post{{ group.posts.count|pluralize }}
					</div>
				</div>
			</div>
		</a>
		{% endfor %}
	</div>
</div>
{% endblock %}